"""Durable full-media ZIP generation, notification and cleanup for RND-360."""

from __future__ import annotations

import base64
import csv
import io
import re
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path

from sqlalchemy import or_, select
from sqlalchemy.orm import Session

from app.db.models import AdminUser, ExportJob, MediaFile
from app.email import send_export_ready_email
from app.media_storage import (
    LocalStorageProvider,
    MediaObjectNotFound,
    MediaStorageConfigurationError,
    MediaStorageOperationError,
    MediaStorageUnavailable,
    build_tenant_media_key,
    get_configured_write_backend_name,
    get_default_media_storage_provider,
    get_media_storage_provider_for_backend,
    object_key_tenant_prefix_matches,
    resolve_effective_storage_reference,
)
from app.settings import get_wecom_oauth_settings


EXPORT_RETENTION_DAYS = 7
EXPORT_LEASE_HOURS = 6
MAX_GENERATION_ATTEMPTS = 3
MAX_NOTIFICATION_ATTEMPTS = 5
# Dora fetches sources asynchronously.  Keep the signed private URLs valid
# through ordinary queueing and a large ZIP build without exposing them to
# clients or storing them outside the short-lived private index object.
EXPORT_SOURCE_URL_TTL_SECONDS = 24 * 60 * 60
MAX_QINIU_EXPORT_OBJECTS = 3000
MAX_QINIU_EXPORT_BYTES = 45_000_000_000
_SAFE_SEGMENT = re.compile(r"[^A-Za-z0-9_.-]+")
_SAFE_SUFFIX = re.compile(r"^\.[A-Za-z0-9]{1,10}$")


@dataclass(frozen=True)
class ExportMaintenanceSummary:
    claimed: int = 0
    ready: int = 0
    retried: int = 0
    failed: int = 0
    notifications_sent: int = 0
    notifications_failed: int = 0
    expired: int = 0
    cleanup_pending: int = 0


@dataclass(frozen=True)
class _QiniuZipSubmission:
    operation_id: str
    index_ref: str
    manifest_ref: str


class ExportSourceIneligibleError(ValueError):
    """A requested media export cannot be built safely by Qiniu mkzip."""


def _utc(value: datetime | None = None) -> datetime:
    current = value or datetime.now(timezone.utc)
    if current.tzinfo is None:
        return current.replace(tzinfo=timezone.utc)
    return current.astimezone(timezone.utc)


def _aware(value: datetime | None) -> datetime | None:
    if value is None:
        return None
    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc)


def create_media_export_job(
    db: Session,
    *,
    tenant_id: str,
    requested_by: str,
    now: datetime | None = None,
) -> ExportJob:
    job = ExportJob(
        id=str(uuid.uuid4()),
        tenant_id=tenant_id,
        requested_by=requested_by,
        kind="media_zip",
        format="zip",
        status="queued",
        notification_status="pending",
        requested_at=_utc(now),
    )
    db.add(job)
    db.flush()
    return job


def export_job_view(job: ExportJob, *, now: datetime | None = None) -> dict:
    checked_at = _utc(now)
    expires_at = _aware(job.expires_at)
    effective_status = job.status
    if job.status == "ready" and expires_at is not None and expires_at <= checked_at:
        effective_status = "expired"
    return {
        "job_id": job.id,
        "kind": job.kind,
        "format": job.format,
        "status": effective_status,
        "file_size": job.file_size,
        "requested_at": _aware(job.requested_at),
        "started_at": _aware(job.started_at),
        "completed_at": _aware(job.completed_at),
        "expires_at": expires_at,
        "notification_status": job.notification_status,
        "notification_retryable": (
            job.notification_status == "failed"
            and int(job.notification_attempts or 0) < MAX_NOTIFICATION_ATTEMPTS
            and effective_status == "ready"
        ),
        "download_available": effective_status == "ready",
    }


def export_storage_reference_is_valid(
    *,
    tenant_id: str,
    job_id: str,
    storage_backend: str | None,
    storage_ref: str | None,
) -> bool:
    """Require the exact tenant/job-scoped key generated by this service."""
    if not storage_backend or not storage_ref:
        return False
    expected_ref = build_tenant_media_key(
        tenant_id, "exports", job_id, suffix=".zip"
    )
    if storage_backend != "local":
        return storage_ref == expected_ref
    try:
        provider = get_media_storage_provider_for_backend("local")
        if not isinstance(provider, LocalStorageProvider) or provider.root is None:
            return False
        actual_path = Path(storage_ref)
        if not actual_path.is_absolute():
            actual_path = provider.root / actual_path
        return actual_path.resolve() == (provider.root / expected_ref).resolve()
    except (OSError, ValueError, MediaStorageConfigurationError):
        return False


def _safe_segment(value: str | None, fallback: str) -> str:
    cleaned = _SAFE_SEGMENT.sub("_", str(value or "")).strip("._")
    return cleaned or fallback


def _safe_suffix(storage_ref: str) -> str:
    suffix = Path(storage_ref).suffix.lower()
    return suffix if _SAFE_SUFFIX.fullmatch(suffix) else ".bin"


def _media_rows(db: Session, tenant_id: str):
    return db.execute(
        select(
            MediaFile.id,
            MediaFile.archive_message_id,
            MediaFile.file_type,
            MediaFile.local_path,
            MediaFile.storage_backend,
            MediaFile.storage_ref,
            MediaFile.file_size,
            MediaFile.checksum_sha256,
        )
        .where(
            MediaFile.tenant_id == tenant_id,
            MediaFile.download_status == "downloaded",
        )
        .order_by(MediaFile.id.asc())
    ).all()


def _qiniu_export_refs(job: ExportJob) -> tuple[str, str, str]:
    """Return deterministic private refs for one Qiniu export job."""
    output_ref = build_tenant_media_key(job.tenant_id, "exports", job.id, suffix=".zip")
    index_ref = build_tenant_media_key(
        job.tenant_id, "export-work", f"{job.id}-index", suffix=".txt"
    )
    manifest_ref = build_tenant_media_key(
        job.tenant_id, "export-work", f"{job.id}-manifest", suffix=".csv"
    )
    return output_ref, index_ref, manifest_ref


def _qiniu_export_provider():
    """Select the only provider permitted to create full-media exports."""
    if get_configured_write_backend_name() != "qiniu_kodo":
        raise ExportSourceIneligibleError("export_qiniu_storage_required")
    provider = get_default_media_storage_provider()
    # Keep the Qiniu SDK import lazy: a local-media deployment must not need
    # the provider module merely to import this service.
    from app.qiniu_storage import QiniuStorageProvider

    if not isinstance(provider, QiniuStorageProvider):
        raise ExportSourceIneligibleError("export_qiniu_storage_required")
    return provider


def _qiniu_export_provider_for_existing_job():
    """Resolve Qiniu explicitly from a persisted export job."""
    provider = get_media_storage_provider_for_backend("qiniu_kodo")
    from app.qiniu_storage import QiniuStorageProvider

    if not isinstance(provider, QiniuStorageProvider):
        raise MediaStorageConfigurationError("qiniu export provider unavailable")
    return provider


def _urlsafe_base64(value: str) -> str:
    return base64.urlsafe_b64encode(value.encode("utf-8")).decode("ascii")


def _qiniu_index_line(source_url: str, archive_path: str) -> str:
    """Make one mode-4 index entry without ever logging its signed URL."""
    return f"/url/{_urlsafe_base64(source_url)}/alias/{_urlsafe_base64(archive_path)}"


def _build_qiniu_manifest_and_index(db: Session, job: ExportJob):
    """Validate the exact export set and create its private Qiniu index data.

    Qiniu Dora will read only the signed URLs generated here.  Source object
    keys are never written into the ZIP manifest or returned to callers.
    """
    provider = _qiniu_export_provider()
    rows = _media_rows(db, job.tenant_id)
    # All remaining work is remote I/O.  Do not retain a database read
    # transaction while validating every source or submitting Dora work.
    db.rollback()
    if len(rows) > MAX_QINIU_EXPORT_OBJECTS:
        raise ExportSourceIneligibleError("export_qiniu_object_limit")

    total_bytes = 0
    manifest_rows: list[list[str | int]] = []
    index_lines: list[str] = []
    for row in rows:
        backend, storage_ref = resolve_effective_storage_reference(
            row.storage_backend,
            row.storage_ref,
            row.local_path,
        )
        if (
            backend != "qiniu_kodo"
            or not storage_ref
            or not object_key_tenant_prefix_matches(storage_ref, job.tenant_id)
        ):
            raise ExportSourceIneligibleError("export_qiniu_source_ineligible")
        expected_size = int(row.file_size or 0)
        actual_checksum, actual_size = provider.get_sha256_and_size(storage_ref)
        if actual_size != expected_size:
            raise MediaStorageOperationError("media size verification failed")
        expected_checksum = str(row.checksum_sha256 or "").strip().lower()
        if expected_checksum and actual_checksum != expected_checksum:
            raise MediaStorageOperationError("media checksum verification failed")
        total_bytes += actual_size
        if total_bytes > MAX_QINIU_EXPORT_BYTES:
            raise ExportSourceIneligibleError("export_qiniu_size_limit")

        category = _safe_segment(row.file_type, "other")
        archive_path = (
            f"media/{category}/{row.archive_message_id}-{row.id}"
            f"{_safe_suffix(storage_ref)}"
        )
        source_url = provider.get_download_url(
            storage_ref, expires_in=EXPORT_SOURCE_URL_TTL_SECONDS
        )
        if not source_url:
            raise ExportSourceIneligibleError("export_qiniu_source_url_unavailable")
        index_lines.append(_qiniu_index_line(source_url, archive_path))
        manifest_rows.append(
            [
                archive_path,
                row.archive_message_id,
                category,
                actual_size,
                actual_checksum,
            ]
        )

    output_ref, index_ref, manifest_ref = _qiniu_export_refs(job)
    manifest = io.StringIO(newline="")
    writer = csv.writer(manifest)
    writer.writerow(["archive_path", "message_id", "media_type", "bytes", "sha256"])
    writer.writerows(manifest_rows)
    provider.save_bytes(manifest_ref, manifest.getvalue().encode("utf-8-sig"))
    manifest_url = provider.get_download_url(
        manifest_ref, expires_in=EXPORT_SOURCE_URL_TTL_SECONDS
    )
    if not manifest_url:
        provider.delete(manifest_ref)
        raise ExportSourceIneligibleError("export_qiniu_source_url_unavailable")
    index_lines.append(_qiniu_index_line(manifest_url, "manifest.csv"))
    try:
        provider.save_bytes(index_ref, ("\n".join(index_lines) + "\n").encode("utf-8"))
        operation_id = provider.submit_media_zip(index_ref, output_ref)
    except Exception:
        provider.delete(index_ref)
        provider.delete(manifest_ref)
        raise
    return _QiniuZipSubmission(operation_id, index_ref, manifest_ref)


def _delete_qiniu_work_refs(job: ExportJob, provider) -> bool:
    """Best-effort cleanup for the short-lived private index and manifest."""
    refs = [job.provider_index_ref, job.provider_manifest_ref]
    cleaned = True
    for ref in refs:
        if not ref:
            continue
        # Treat an already-deleted object as clean.  This makes retries
        # idempotent even when a previous cleanup deleted only one ref.
        if provider.exists(ref):
            cleaned = provider.delete(ref) and cleaned
    return cleaned


def _clear_qiniu_work_refs(db: Session, job_id: str, *, cleanup_pending: bool) -> None:
    job = db.scalar(select(ExportJob).where(ExportJob.id == job_id).with_for_update())
    if job is None:
        db.rollback()
        return
    if cleanup_pending:
        job.last_error = "cleanup_pending"
    else:
        job.provider_index_ref = None
        job.provider_manifest_ref = None
        if job.last_error == "cleanup_pending":
            job.last_error = None
    db.commit()


def _mark_qiniu_submission(
    db: Session, job_id: str, submission: _QiniuZipSubmission, now: datetime
) -> None:
    job = db.scalar(select(ExportJob).where(ExportJob.id == job_id).with_for_update())
    if job is None:
        db.rollback()
        return
    job.storage_backend = "qiniu_kodo"
    job.provider_operation_id = submission.operation_id
    job.provider_index_ref = submission.index_ref
    job.provider_manifest_ref = submission.manifest_ref
    job.lease_expires_at = now + timedelta(hours=EXPORT_LEASE_HOURS)
    job.last_error = None
    db.commit()


def _mark_qiniu_ready(db: Session, job_id: str, file_size: int, now: datetime) -> None:
    job = db.scalar(select(ExportJob).where(ExportJob.id == job_id).with_for_update())
    if job is None:
        db.rollback()
        return
    output_ref, _index_ref, _manifest_ref = _qiniu_export_refs(job)
    job.status = "ready"
    job.storage_backend = "qiniu_kodo"
    job.storage_ref = output_ref
    job.file_size = file_size
    job.checksum_sha256 = None
    job.completed_at = now
    job.expires_at = now + timedelta(days=EXPORT_RETENTION_DAYS)
    job.lease_expires_at = None
    job.last_error = None
    job.notification_status = "pending"
    db.commit()


def _mark_qiniu_poll_pending(
    db: Session, job_id: str, error: Exception, now: datetime
) -> None:
    """Keep an already-submitted PFOP operation authoritative on outages.

    Re-submitting after an ambiguous status-query failure could create two
    Dora archives for one user request.  Preserve the provider operation ID
    and poll it again after the lease is extended instead.
    """
    db.rollback()
    job = db.scalar(select(ExportJob).where(ExportJob.id == job_id).with_for_update())
    if job is None:
        db.rollback()
        return
    if job.status == "processing" and job.provider_operation_id:
        job.last_error = _failure_tag(error)
        job.lease_expires_at = now + timedelta(hours=EXPORT_LEASE_HOURS)
        db.commit()
        return
    db.rollback()


def _poll_qiniu_media_exports(
    db: Session, *, now: datetime, limit: int
) -> tuple[int, int, int]:
    """Advance submitted Dora jobs without rebuilding their ZIPs locally."""
    ready = retried = failed = 0
    jobs = db.scalars(
        select(ExportJob)
        .where(
            ExportJob.status == "processing",
            ExportJob.storage_backend == "qiniu_kodo",
            ExportJob.provider_operation_id.is_not(None),
        )
        .order_by(ExportJob.started_at.asc())
        .with_for_update(skip_locked=True)
        .limit(max(1, limit))
    ).all()
    for claimed_job in jobs:
        job_id = claimed_job.id
        try:
            provider = _qiniu_export_provider_for_existing_job()
            status = provider.get_persistent_operation_status(
                claimed_job.provider_operation_id
            )
            if status.state == "processing":
                claimed_job.lease_expires_at = now + timedelta(hours=EXPORT_LEASE_HOURS)
                claimed_job.last_error = None
                db.commit()
                continue
            output_ref, _index_ref, _manifest_ref = _qiniu_export_refs(claimed_job)
            if status.state != "succeeded" or not provider.exists(output_ref):
                raise MediaStorageOperationError("qiniu media ZIP processing failed")
            _mark_qiniu_ready(db, job_id, provider.size_bytes(output_ref), now)
            try:
                refreshed = db.scalar(select(ExportJob).where(ExportJob.id == job_id))
                if refreshed is not None:
                    _clear_qiniu_work_refs(
                        db,
                        job_id,
                        cleanup_pending=not _delete_qiniu_work_refs(refreshed, provider),
                    )
            except (
                MediaStorageConfigurationError,
                MediaStorageUnavailable,
                MediaStorageOperationError,
            ):
                _clear_qiniu_work_refs(db, job_id, cleanup_pending=True)
            ready += 1
        except (MediaStorageConfigurationError, MediaStorageUnavailable) as error:
            _mark_qiniu_poll_pending(db, job_id, error, now)
        except Exception as error:  # noqa: BLE001 - persist fixed error tags only
            outcome = _mark_generation_error(db, job_id, error, now)
            if outcome == "retried":
                retried += 1
            else:
                failed += 1
    return ready, retried, failed


def _claim_next_job(db: Session, now: datetime) -> ExportJob | None:
    job = db.scalar(
        select(ExportJob)
        .where(
            or_(
                ExportJob.status == "queued",
                (
                    (ExportJob.status == "processing")
                    & (ExportJob.provider_operation_id.is_(None))
                    & (ExportJob.lease_expires_at.is_not(None))
                    & (ExportJob.lease_expires_at <= now)
                ),
            )
        )
        .order_by(ExportJob.requested_at.asc())
        .with_for_update(skip_locked=True)
        .limit(1)
    )
    if job is None:
        db.rollback()
        return None
    job.status = "processing"
    job.started_at = now
    job.lease_expires_at = now + timedelta(hours=EXPORT_LEASE_HOURS)
    job.attempt_count = int(job.attempt_count or 0) + 1
    job.last_error = None
    db.commit()
    return job


def _failure_tag(error: Exception) -> str:
    if isinstance(error, ExportSourceIneligibleError):
        return str(error)
    if isinstance(error, MediaObjectNotFound):
        return "media_missing"
    if isinstance(error, MediaStorageConfigurationError):
        return "storage_misconfigured"
    if isinstance(error, MediaStorageUnavailable):
        return "storage_unavailable"
    if isinstance(error, MediaStorageOperationError):
        return "storage_operation_failed"
    if isinstance(error, OSError):
        return "local_io_failed"
    return "generation_failed"


def _mark_generation_error(
    db: Session, job_id: str, error: Exception, now: datetime
) -> str:
    db.rollback()
    job = db.scalar(select(ExportJob).where(ExportJob.id == job_id).with_for_update())
    if job is None:
        db.rollback()
        return "failed"
    job.last_error = _failure_tag(error)
    job.lease_expires_at = None
    # A failed Dora operation must never be polled again.  The deterministic
    # work refs are retained until a successful retry or cleanup can remove
    # them; this also avoids losing the only safe cleanup targets.
    job.provider_operation_id = None
    if int(job.attempt_count or 0) < MAX_GENERATION_ATTEMPTS:
        job.status = "queued"
        result = "retried"
    else:
        job.status = "failed"
        job.completed_at = now
        result = "failed"
    db.commit()
    return result


def _notification_link(job_id: str) -> str | None:
    domain = (get_wecom_oauth_settings().admin_domain or "").strip()
    if not domain:
        return None
    for prefix in ("https://", "http://"):
        if domain.lower().startswith(prefix):
            domain = domain[len(prefix) :]
            break
    domain = domain.strip("/")
    if not domain:
        return None
    base = f"https://{domain}"
    return f"{base}/admin/exports?job={job_id}"


def send_pending_export_notifications(
    db: Session, *, now: datetime | None = None, limit: int = 10
) -> tuple[int, int]:
    checked_at = _utc(now)
    sent = 0
    failed = 0
    for _ in range(max(1, limit)):
        # Keep the row lock through the SMTP attempt. A second manually
        # started worker skips the row instead of sending a duplicate mail.
        job = db.scalar(
            select(ExportJob)
            .where(
                ExportJob.status == "ready",
                ExportJob.expires_at > checked_at,
                ExportJob.notification_status.in_(("pending", "failed")),
                ExportJob.notification_attempts < MAX_NOTIFICATION_ATTEMPTS,
            )
            .order_by(ExportJob.completed_at.asc())
            .with_for_update(skip_locked=True)
            .limit(1)
        )
        if job is None:
            db.rollback()
            break
        owner = db.scalar(
            select(AdminUser).where(
                AdminUser.id == job.requested_by,
                AdminUser.tenant_id == job.tenant_id,
                AdminUser.role == "owner",
                AdminUser.status == "active",
            )
        )
        link = _notification_link(job.id)
        recipient = (owner.email or "").strip() if owner else ""
        success = bool(
            owner
            and "@" in recipient
            and not recipient.startswith("@")
            and link
            and send_export_ready_email(
                recipient,
                link,
                _aware(job.expires_at) or checked_at,
                owner.ui_locale or "zh-CN",
            )
        )
        job.notification_attempts = int(job.notification_attempts or 0) + 1
        job.notification_last_attempt_at = checked_at
        if success:
            job.notification_status = "sent"
            job.notification_sent_at = checked_at
            sent += 1
        else:
            job.notification_status = "failed"
            failed += 1
        db.commit()
    return sent, failed


def cleanup_expired_exports(
    db: Session, *, now: datetime | None = None, limit: int = 20
) -> tuple[int, int]:
    checked_at = _utc(now)
    jobs = db.scalars(
        select(ExportJob)
        .where(
            ExportJob.status == "ready",
            ExportJob.expires_at.is_not(None),
            ExportJob.expires_at <= checked_at,
        )
        .order_by(ExportJob.expires_at.asc())
        .limit(max(1, limit))
    ).all()
    expired = 0
    pending = 0
    for job in jobs:
        deleted = False
        try:
            if not job.storage_backend or not job.storage_ref:
                deleted = True
            elif not export_storage_reference_is_valid(
                tenant_id=job.tenant_id,
                job_id=job.id,
                storage_backend=job.storage_backend,
                storage_ref=job.storage_ref,
            ):
                deleted = False
            else:
                provider = (
                    _qiniu_export_provider_for_existing_job()
                    if job.storage_backend == "qiniu_kodo"
                    else get_media_storage_provider_for_backend(job.storage_backend)
                )
                if not provider.exists(job.storage_ref):
                    deleted = True
                else:
                    deleted = provider.delete(job.storage_ref)
                if deleted and job.storage_backend == "qiniu_kodo":
                    deleted = _delete_qiniu_work_refs(job, provider)
        except (
            MediaStorageConfigurationError,
            MediaStorageUnavailable,
            MediaStorageOperationError,
        ):
            deleted = False
        if deleted:
            job.status = "expired"
            job.storage_ref = None
            job.provider_index_ref = None
            job.provider_manifest_ref = None
            job.last_error = None
            expired += 1
        else:
            job.last_error = "cleanup_pending"
            pending += 1
        db.commit()
    return expired, pending


def cleanup_terminal_qiniu_export_work(db: Session, *, limit: int = 20) -> int:
    """Remove index/manifest objects left by completed Dora jobs.

    A success normally deletes these immediately.  Keeping a separate,
    idempotent maintenance pass closes the gap if one delete call had a
    transient provider failure after the ZIP became ready.
    """
    jobs = db.scalars(
        select(ExportJob)
        .where(
            ExportJob.status.in_(("ready", "failed", "expired")),
            ExportJob.storage_backend == "qiniu_kodo",
            (ExportJob.provider_index_ref.is_not(None))
            | (ExportJob.provider_manifest_ref.is_not(None)),
        )
        .order_by(ExportJob.completed_at.asc())
        .limit(max(1, limit))
    ).all()
    pending = 0
    for job in jobs:
        try:
            provider = _qiniu_export_provider_for_existing_job()
            cleaned = _delete_qiniu_work_refs(job, provider)
        except (
            MediaStorageConfigurationError,
            MediaStorageUnavailable,
            MediaStorageOperationError,
        ):
            cleaned = False
        if cleaned:
            job.provider_index_ref = None
            job.provider_manifest_ref = None
            if job.last_error == "cleanup_pending":
                job.last_error = None
        else:
            job.last_error = "cleanup_pending"
            pending += 1
        db.commit()
    return pending


def run_export_maintenance_once(
    db: Session,
    *,
    now: datetime | None = None,
    generation_limit: int = 1,
) -> ExportMaintenanceSummary:
    checked_at = _utc(now)
    claimed = failed = 0
    ready, retried, failed = _poll_qiniu_media_exports(
        db, now=checked_at, limit=generation_limit
    )
    for _ in range(max(1, generation_limit)):
        job = _claim_next_job(db, checked_at)
        if job is None:
            break
        claimed += 1
        try:
            submission = _build_qiniu_manifest_and_index(db, job)
            _mark_qiniu_submission(db, job.id, submission, checked_at)
        except Exception as error:  # noqa: BLE001 - persist only a fixed tag
            outcome = _mark_generation_error(db, job.id, error, checked_at)
            if outcome == "retried":
                retried += 1
            else:
                failed += 1

    notifications_sent, notifications_failed = send_pending_export_notifications(
        db, now=checked_at
    )
    terminal_work_pending = cleanup_terminal_qiniu_export_work(db)
    expired, cleanup_pending = cleanup_expired_exports(db, now=checked_at)
    return ExportMaintenanceSummary(
        claimed=claimed,
        ready=ready,
        retried=retried,
        failed=failed,
        notifications_sent=notifications_sent,
        notifications_failed=notifications_failed,
        expired=expired,
        cleanup_pending=cleanup_pending + terminal_work_pending,
    )
