"""Durable full-media ZIP generation, notification and cleanup for RND-360."""

from __future__ import annotations

import csv
import hashlib
import io
import re
import tempfile
import uuid
import zipfile
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path

from sqlalchemy import or_, select
from sqlalchemy.orm import Session

from app.db.models import AdminUser, ExportJob, MediaFile
from app.email import send_export_ready_email
from app.media_storage import (
    LocalStorageProvider,
    MediaObjectNotFound,
    MediaStorageConfigurationError,
    MediaStorageOperationError,
    MediaStorageUnavailable,
    build_tenant_media_key,
    get_configured_write_backend_name,
    get_default_media_storage_provider,
    get_media_storage_provider_for_backend,
    object_key_tenant_prefix_matches,
    resolve_effective_storage_reference,
)
from app.settings import get_wecom_oauth_settings


EXPORT_RETENTION_DAYS = 7
EXPORT_LEASE_HOURS = 6
MAX_GENERATION_ATTEMPTS = 3
MAX_NOTIFICATION_ATTEMPTS = 5
_SAFE_SEGMENT = re.compile(r"[^A-Za-z0-9_.-]+")
_SAFE_SUFFIX = re.compile(r"^\.[A-Za-z0-9]{1,10}$")


@dataclass(frozen=True)
class ExportMaintenanceSummary:
    claimed: int = 0
    ready: int = 0
    retried: int = 0
    failed: int = 0
    notifications_sent: int = 0
    notifications_failed: int = 0
    expired: int = 0
    cleanup_pending: int = 0


@dataclass(frozen=True)
class _Artifact:
    storage_backend: str
    storage_ref: str
    file_size: int
    checksum_sha256: str


def _utc(value: datetime | None = None) -> datetime:
    current = value or datetime.now(timezone.utc)
    if current.tzinfo is None:
        return current.replace(tzinfo=timezone.utc)
    return current.astimezone(timezone.utc)


def _aware(value: datetime | None) -> datetime | None:
    if value is None:
        return None
    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc)


def create_media_export_job(
    db: Session,
    *,
    tenant_id: str,
    requested_by: str,
    now: datetime | None = None,
) -> ExportJob:
    job = ExportJob(
        id=str(uuid.uuid4()),
        tenant_id=tenant_id,
        requested_by=requested_by,
        kind="media_zip",
        format="zip",
        status="queued",
        notification_status="pending",
        requested_at=_utc(now),
    )
    db.add(job)
    db.flush()
    return job


def export_job_view(job: ExportJob, *, now: datetime | None = None) -> dict:
    checked_at = _utc(now)
    expires_at = _aware(job.expires_at)
    effective_status = job.status
    if job.status == "ready" and expires_at is not None and expires_at <= checked_at:
        effective_status = "expired"
    return {
        "job_id": job.id,
        "kind": job.kind,
        "format": job.format,
        "status": effective_status,
        "file_size": job.file_size,
        "requested_at": _aware(job.requested_at),
        "started_at": _aware(job.started_at),
        "completed_at": _aware(job.completed_at),
        "expires_at": expires_at,
        "notification_status": job.notification_status,
        "notification_retryable": (
            job.notification_status == "failed"
            and int(job.notification_attempts or 0) < MAX_NOTIFICATION_ATTEMPTS
            and effective_status == "ready"
        ),
        "download_available": effective_status == "ready",
    }


def export_storage_reference_is_valid(
    *,
    tenant_id: str,
    job_id: str,
    storage_backend: str | None,
    storage_ref: str | None,
) -> bool:
    """Require the exact tenant/job-scoped key generated by this service."""
    if not storage_backend or not storage_ref:
        return False
    expected_ref = build_tenant_media_key(
        tenant_id, "exports", job_id, suffix=".zip"
    )
    if storage_backend != "local":
        return storage_ref == expected_ref
    try:
        provider = get_media_storage_provider_for_backend("local")
        if not isinstance(provider, LocalStorageProvider) or provider.root is None:
            return False
        actual_path = Path(storage_ref)
        if not actual_path.is_absolute():
            actual_path = provider.root / actual_path
        return actual_path.resolve() == (provider.root / expected_ref).resolve()
    except (OSError, ValueError, MediaStorageConfigurationError):
        return False


def _safe_segment(value: str | None, fallback: str) -> str:
    cleaned = _SAFE_SEGMENT.sub("_", str(value or "")).strip("._")
    return cleaned or fallback


def _safe_suffix(storage_ref: str) -> str:
    suffix = Path(storage_ref).suffix.lower()
    return suffix if _SAFE_SUFFIX.fullmatch(suffix) else ".bin"


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _media_rows(db: Session, tenant_id: str):
    return db.execute(
        select(
            MediaFile.id,
            MediaFile.archive_message_id,
            MediaFile.file_type,
            MediaFile.local_path,
            MediaFile.storage_backend,
            MediaFile.storage_ref,
            MediaFile.file_size,
            MediaFile.checksum_sha256,
        )
        .where(
            MediaFile.tenant_id == tenant_id,
            MediaFile.download_status == "downloaded",
        )
        .order_by(MediaFile.id.asc())
    ).all()


def _source_path_for_row(
    row, tenant_id: str, scratch: Path
) -> tuple[Path, str, int, bool]:
    backend, storage_ref = resolve_effective_storage_reference(
        row.storage_backend,
        row.storage_ref,
        row.local_path,
    )
    if not backend or not storage_ref:
        raise MediaObjectNotFound("downloaded media has no storage reference")
    if backend == "qiniu_kodo" and not object_key_tenant_prefix_matches(
        storage_ref, tenant_id
    ):
        raise MediaStorageConfigurationError("media object tenant prefix mismatch")

    provider = get_media_storage_provider_for_backend(backend)
    local_path = provider.get_local_path(storage_ref) if provider.supports_local_path() else None
    if local_path is not None:
        actual_size = local_path.stat().st_size
        return local_path, storage_ref, actual_size, False

    scratch_path = scratch / f"source-{row.id}"
    actual_size = provider.copy_to_file(storage_ref, scratch_path)
    return scratch_path, storage_ref, actual_size, True


def _build_media_zip(db: Session, job: ExportJob) -> _Artifact:
    job_id = job.id
    tenant_id = job.tenant_id
    rows = _media_rows(db, tenant_id)
    # The remaining work is storage/network I/O.  Do not keep a database read
    # transaction open while a multi-gigabyte archive is assembled.
    db.rollback()
    with tempfile.TemporaryDirectory(prefix="wecom-media-export-") as temp_dir:
        temp_root = Path(temp_dir)
        zip_path = temp_root / f"{job.id}.zip"
        manifest_rows: list[list[str | int]] = []
        with zipfile.ZipFile(
            zip_path, "w", compression=zipfile.ZIP_STORED, allowZip64=True
        ) as archive:
            for row in rows:
                source_path, storage_ref, actual_size, is_temporary = _source_path_for_row(
                    row, tenant_id, temp_root
                )
                expected_size = int(row.file_size or 0)
                if actual_size != expected_size:
                    raise MediaStorageOperationError("media size verification failed")
                checksum = _sha256_file(source_path)
                if row.checksum_sha256 and checksum != row.checksum_sha256:
                    raise MediaStorageOperationError("media checksum verification failed")

                category = _safe_segment(row.file_type, "other")
                arcname = (
                    f"media/{category}/{row.archive_message_id}-{row.id}"
                    f"{_safe_suffix(storage_ref)}"
                )
                archive.write(source_path, arcname=arcname)
                manifest_rows.append(
                    [arcname, row.archive_message_id, category, actual_size, checksum]
                )
                if is_temporary:
                    source_path.unlink(missing_ok=True)

            manifest = io.StringIO(newline="")
            writer = csv.writer(manifest)
            writer.writerow(
                ["archive_path", "message_id", "media_type", "bytes", "sha256"]
            )
            writer.writerows(manifest_rows)
            archive.writestr("manifest.csv", manifest.getvalue().encode("utf-8-sig"))

        artifact_size = zip_path.stat().st_size
        artifact_checksum = _sha256_file(zip_path)
        backend = get_configured_write_backend_name()
        provider = get_default_media_storage_provider()
        target_ref = build_tenant_media_key(
            tenant_id, "exports", job_id, suffix=".zip"
        )
        stored_ref = provider.save_file(target_ref, zip_path)
        if not export_storage_reference_is_valid(
            tenant_id=tenant_id,
            job_id=job_id,
            storage_backend=backend,
            storage_ref=stored_ref,
        ):
            raise MediaStorageConfigurationError(
                "export storage reference does not match tenant job scope"
            )
        return _Artifact(
            storage_backend=backend,
            storage_ref=stored_ref,
            file_size=artifact_size,
            checksum_sha256=artifact_checksum,
        )


def _claim_next_job(db: Session, now: datetime) -> ExportJob | None:
    job = db.scalar(
        select(ExportJob)
        .where(
            or_(
                ExportJob.status == "queued",
                (
                    (ExportJob.status == "processing")
                    & (ExportJob.lease_expires_at.is_not(None))
                    & (ExportJob.lease_expires_at <= now)
                ),
            )
        )
        .order_by(ExportJob.requested_at.asc())
        .with_for_update(skip_locked=True)
        .limit(1)
    )
    if job is None:
        db.rollback()
        return None
    job.status = "processing"
    job.started_at = now
    job.lease_expires_at = now + timedelta(hours=EXPORT_LEASE_HOURS)
    job.attempt_count = int(job.attempt_count or 0) + 1
    job.last_error = None
    db.commit()
    return job


def _mark_ready(db: Session, job_id: str, artifact: _Artifact, now: datetime) -> None:
    job = db.scalar(select(ExportJob).where(ExportJob.id == job_id).with_for_update())
    if job is None:
        db.rollback()
        return
    job.status = "ready"
    job.storage_backend = artifact.storage_backend
    job.storage_ref = artifact.storage_ref
    job.file_size = artifact.file_size
    job.checksum_sha256 = artifact.checksum_sha256
    job.completed_at = now
    job.expires_at = now + timedelta(days=EXPORT_RETENTION_DAYS)
    job.lease_expires_at = None
    job.last_error = None
    job.notification_status = "pending"
    db.commit()


def _failure_tag(error: Exception) -> str:
    if isinstance(error, MediaObjectNotFound):
        return "media_missing"
    if isinstance(error, MediaStorageConfigurationError):
        return "storage_misconfigured"
    if isinstance(error, MediaStorageUnavailable):
        return "storage_unavailable"
    if isinstance(error, MediaStorageOperationError):
        return "storage_operation_failed"
    if isinstance(error, OSError):
        return "local_io_failed"
    return "generation_failed"


def _mark_generation_error(
    db: Session, job_id: str, error: Exception, now: datetime
) -> str:
    db.rollback()
    job = db.scalar(select(ExportJob).where(ExportJob.id == job_id).with_for_update())
    if job is None:
        db.rollback()
        return "failed"
    job.last_error = _failure_tag(error)
    job.lease_expires_at = None
    if int(job.attempt_count or 0) < MAX_GENERATION_ATTEMPTS:
        job.status = "queued"
        result = "retried"
    else:
        job.status = "failed"
        job.completed_at = now
        result = "failed"
    db.commit()
    return result


def _notification_link(job_id: str) -> str | None:
    domain = (get_wecom_oauth_settings().admin_domain or "").strip()
    if not domain:
        return None
    for prefix in ("https://", "http://"):
        if domain.lower().startswith(prefix):
            domain = domain[len(prefix) :]
            break
    domain = domain.strip("/")
    if not domain:
        return None
    base = f"https://{domain}"
    return f"{base}/admin/exports?job={job_id}"


def send_pending_export_notifications(
    db: Session, *, now: datetime | None = None, limit: int = 10
) -> tuple[int, int]:
    checked_at = _utc(now)
    sent = 0
    failed = 0
    for _ in range(max(1, limit)):
        # Keep the row lock through the SMTP attempt. A second manually
        # started worker skips the row instead of sending a duplicate mail.
        job = db.scalar(
            select(ExportJob)
            .where(
                ExportJob.status == "ready",
                ExportJob.expires_at > checked_at,
                ExportJob.notification_status.in_(("pending", "failed")),
                ExportJob.notification_attempts < MAX_NOTIFICATION_ATTEMPTS,
            )
            .order_by(ExportJob.completed_at.asc())
            .with_for_update(skip_locked=True)
            .limit(1)
        )
        if job is None:
            db.rollback()
            break
        owner = db.scalar(
            select(AdminUser).where(
                AdminUser.id == job.requested_by,
                AdminUser.tenant_id == job.tenant_id,
                AdminUser.role == "owner",
                AdminUser.status == "active",
            )
        )
        link = _notification_link(job.id)
        recipient = (owner.email or "").strip() if owner else ""
        success = bool(
            owner
            and "@" in recipient
            and not recipient.startswith("@")
            and link
            and send_export_ready_email(
                recipient,
                link,
                _aware(job.expires_at) or checked_at,
                owner.ui_locale or "zh-CN",
            )
        )
        job.notification_attempts = int(job.notification_attempts or 0) + 1
        job.notification_last_attempt_at = checked_at
        if success:
            job.notification_status = "sent"
            job.notification_sent_at = checked_at
            sent += 1
        else:
            job.notification_status = "failed"
            failed += 1
        db.commit()
    return sent, failed


def cleanup_expired_exports(
    db: Session, *, now: datetime | None = None, limit: int = 20
) -> tuple[int, int]:
    checked_at = _utc(now)
    jobs = db.scalars(
        select(ExportJob)
        .where(
            ExportJob.status == "ready",
            ExportJob.expires_at.is_not(None),
            ExportJob.expires_at <= checked_at,
        )
        .order_by(ExportJob.expires_at.asc())
        .limit(max(1, limit))
    ).all()
    expired = 0
    pending = 0
    for job in jobs:
        deleted = False
        try:
            if not job.storage_backend or not job.storage_ref:
                deleted = True
            elif not export_storage_reference_is_valid(
                tenant_id=job.tenant_id,
                job_id=job.id,
                storage_backend=job.storage_backend,
                storage_ref=job.storage_ref,
            ):
                deleted = False
            else:
                provider = get_media_storage_provider_for_backend(job.storage_backend)
                if not provider.exists(job.storage_ref):
                    deleted = True
                else:
                    deleted = provider.delete(job.storage_ref)
        except (
            MediaStorageConfigurationError,
            MediaStorageUnavailable,
            MediaStorageOperationError,
        ):
            deleted = False
        if deleted:
            job.status = "expired"
            job.storage_ref = None
            job.last_error = None
            expired += 1
        else:
            job.last_error = "cleanup_pending"
            pending += 1
        db.commit()
    return expired, pending


def run_export_maintenance_once(
    db: Session,
    *,
    now: datetime | None = None,
    generation_limit: int = 1,
) -> ExportMaintenanceSummary:
    checked_at = _utc(now)
    claimed = ready = retried = failed = 0
    for _ in range(max(1, generation_limit)):
        job = _claim_next_job(db, checked_at)
        if job is None:
            break
        claimed += 1
        try:
            artifact = _build_media_zip(db, job)
            completed_at = checked_at if now is not None else _utc()
            _mark_ready(db, job.id, artifact, completed_at)
            ready += 1
        except Exception as error:  # noqa: BLE001 - persist only a fixed tag
            outcome = _mark_generation_error(db, job.id, error, checked_at)
            if outcome == "retried":
                retried += 1
            else:
                failed += 1

    notifications_sent, notifications_failed = send_pending_export_notifications(
        db, now=checked_at
    )
    expired, cleanup_pending = cleanup_expired_exports(db, now=checked_at)
    return ExportMaintenanceSummary(
        claimed=claimed,
        ready=ready,
        retried=retried,
        failed=failed,
        notifications_sent=notifications_sent,
        notifications_failed=notifications_failed,
        expired=expired,
        cleanup_pending=cleanup_pending,
    )
